name: Continuous integration

on:
  push:
  pull_request:
    branches:
      - "*"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run static code analysis
        run: |
          npm run format
          npm run type-check
          npm run lint

      - name: Run unit tests
        run: |
          npm run test:ci
